name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Gerar EXE
        run: npm run dist -- --publish never

      - name: Enviar arquivos gerados
        uses: actions/upload-artifact@v4
        with:
          name: JotasBrain-Windows
          path: dist/**